// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PracticeX.Infrastructure.Persistence;

#nullable disable

namespace PracticeX.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PracticeXDbContext))]
    [Migration("20260425181152_initial_enterprise_foundation")]
    partial class initial_enterprise_foundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PracticeX.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("event_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("NewValueHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("new_value_hash");

                    b.Property<string>("PriorValueHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("prior_value_hash");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_audit_events_resource_type_resource_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_tenant_id_created_at");

                    b.ToTable("audit_events", "audit");
                });

            modelBuilder.Entity("PracticeX.Domain.Contracts.ContractField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("field_key");

                    b.Property<string>("NormalizedValue")
                        .HasColumnType("text")
                        .HasColumnName("normalized_value");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("review_status");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<JsonDocument>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Id")
                        .HasName("pk_contract_fields");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contract_fields_tenant_id");

                    b.HasIndex("ContractId", "FieldKey", "SchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_contract_fields_contract_id_field_key_schema_version");

                    b.ToTable("contract_fields", "contract");
                });

            modelBuilder.Entity("PracticeX.Domain.Contracts.ContractRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("contract_type");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("ix_contracts_counterparty_id");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_contracts_facility_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_contracts_owner_user_id");

                    b.HasIndex("TenantId", "FacilityId", "Status")
                        .HasDatabaseName("ix_contracts_tenant_id_facility_id_status");

                    b.ToTable("contracts", "contract");
                });

            modelBuilder.Entity("PracticeX.Domain.Contracts.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Aliases")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("aliases");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("PayerIdentifier")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("payer_identifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_counterparties");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_counterparties_tenant_id_name");

                    b.ToTable("counterparties", "contract");
                });

            modelBuilder.Entity("PracticeX.Domain.Documents.DocumentAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ocr_status");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid?>("SourceObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_object_id");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("storage_uri");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TextStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("text_status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_assets");

                    b.HasIndex("SourceObjectId")
                        .HasDatabaseName("ix_document_assets_source_object_id");

                    b.HasIndex("TenantId", "Sha256")
                        .IsUnique()
                        .HasDatabaseName("ix_document_assets_tenant_id_sha256");

                    b.ToTable("document_assets", "doc");
                });

            modelBuilder.Entity("PracticeX.Domain.Documents.DocumentCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CandidateType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("candidate_type");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("CounterpartyHint")
                        .HasColumnType("text")
                        .HasColumnName("counterparty_hint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_asset_id");

                    b.Property<Guid?>("FacilityHintId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_hint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_candidates");

                    b.HasIndex("DocumentAssetId")
                        .HasDatabaseName("ix_document_candidates_document_asset_id");

                    b.HasIndex("FacilityHintId")
                        .HasDatabaseName("ix_document_candidates_facility_hint_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_document_candidates_tenant_id_status");

                    b.ToTable("document_candidates", "doc");
                });

            modelBuilder.Entity("PracticeX.Domain.Documents.IngestionBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_batches");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_ingestion_batches_created_by_user_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_ingestion_batches_tenant_id_created_at");

                    b.ToTable("ingestion_batches", "doc");
                });

            modelBuilder.Entity("PracticeX.Domain.Documents.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DocumentAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_asset_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("SourceObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_object_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_jobs");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_ingestion_jobs_batch_id");

                    b.HasIndex("DocumentAssetId")
                        .HasDatabaseName("ix_ingestion_jobs_document_asset_id");

                    b.HasIndex("SourceObjectId")
                        .HasDatabaseName("ix_ingestion_jobs_source_object_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_ingestion_jobs_tenant_id_status");

                    b.ToTable("ingestion_jobs", "doc");
                });

            modelBuilder.Entity("PracticeX.Domain.Evidence.EvidenceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_asset_id");

                    b.Property<JsonDocument>("PageRefs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("page_refs");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("resource_type");

                    b.Property<Guid?>("SourceObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_object_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_evidence_links");

                    b.HasIndex("DocumentAssetId")
                        .HasDatabaseName("ix_evidence_links_document_asset_id");

                    b.HasIndex("SourceObjectId")
                        .HasDatabaseName("ix_evidence_links_source_object_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_evidence_links_tenant_id");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_evidence_links_resource_type_resource_id");

                    b.ToTable("evidence_links", "evidence");
                });

            modelBuilder.Entity("PracticeX.Domain.Organization.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.ToTable("users", "org");
                });

            modelBuilder.Entity("PracticeX.Domain.Organization.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<string>("Npi")
                        .HasColumnType("text")
                        .HasColumnName("npi");

                    b.Property<string>("Specialty")
                        .HasColumnType("text")
                        .HasColumnName("specialty");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TaxId")
                        .HasColumnType("text")
                        .HasColumnName("tax_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_facilities");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_facilities_tenant_id_code");

                    b.ToTable("facilities", "org");
                });

            modelBuilder.Entity("PracticeX.Domain.Organization.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_roles_tenant_id");

                    b.ToTable("roles", "org");
                });

            modelBuilder.Entity("PracticeX.Domain.Organization.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_role_assignments");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_role_assignments_facility_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_assignments_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_role_assignments_user_id");

                    b.HasIndex("TenantId", "UserId", "FacilityId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_role_assignments_tenant_id_user_id_facility_id_role_id");

                    b.ToTable("role_assignments", "org");
                });

            modelBuilder.Entity("PracticeX.Domain.Organization.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaaStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("baa_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataRegion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("data_region");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "org");
                });

            modelBuilder.Entity("PracticeX.Domain.Sources.SourceConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("OauthSubject")
                        .HasColumnType("text")
                        .HasColumnName("oauth_subject");

                    b.Property<string>("ScopeSet")
                        .HasColumnType("text")
                        .HasColumnName("scope_set");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_source_connections");

                    b.HasIndex("TenantId", "SourceType", "DisplayName")
                        .HasDatabaseName("ix_source_connections_tenant_id_source_type_display_name");

                    b.ToTable("source_connections", "doc");
                });

            modelBuilder.Entity("PracticeX.Domain.Sources.SourceObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<DateTimeOffset?>("SourceCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_created_at");

                    b.Property<DateTimeOffset?>("SourceModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_modified_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_source_objects");

                    b.HasIndex("ConnectionId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_source_objects_connection_id_external_id");

                    b.HasIndex("TenantId", "Sha256")
                        .HasDatabaseName("ix_source_objects_tenant_id_sha256");

                    b.ToTable("source_objects", "doc");
                });

            modelBuilder.Entity("PracticeX.Domain.Workflow.ReviewTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("decision");

                    b.Property<int?>("EffortSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("effort_seconds");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_review_tasks");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_review_tasks_assigned_to_user_id");

                    b.HasIndex("TenantId", "Decision", "Priority")
                        .HasDatabaseName("ix_review_tasks_tenant_id_decision_priority");

                    b.ToTable("review_tasks", "workflow");
                });

            modelBuilder.Entity("PracticeX.Domain.Audit.AuditEvent", b =>
                {
                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Contracts.ContractField", b =>
                {
                    b.HasOne("PracticeX.Domain.Contracts.ContractRecord", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_fields_contracts_contract_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_fields_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Contracts.ContractRecord", b =>
                {
                    b.HasOne("PracticeX.Domain.Contracts.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_counterparties_counterparty_id");

                    b.HasOne("PracticeX.Domain.Organization.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_facilities_facility_id");

                    b.HasOne("PracticeX.Domain.Organization.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contracts_users_owner_user_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Contracts.Counterparty", b =>
                {
                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_counterparties_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Documents.DocumentAsset", b =>
                {
                    b.HasOne("PracticeX.Domain.Sources.SourceObject", null)
                        .WithMany()
                        .HasForeignKey("SourceObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_document_assets_source_objects_source_object_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_assets_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Documents.DocumentCandidate", b =>
                {
                    b.HasOne("PracticeX.Domain.Documents.DocumentAsset", null)
                        .WithMany()
                        .HasForeignKey("DocumentAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_candidates_document_assets_document_asset_id");

                    b.HasOne("PracticeX.Domain.Organization.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityHintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_document_candidates_facilities_facility_hint_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_candidates_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Documents.IngestionBatch", b =>
                {
                    b.HasOne("PracticeX.Domain.Organization.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_batches_users_created_by_user_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_batches_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Documents.IngestionJob", b =>
                {
                    b.HasOne("PracticeX.Domain.Documents.IngestionBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_jobs_ingestion_batches_batch_id");

                    b.HasOne("PracticeX.Domain.Documents.DocumentAsset", null)
                        .WithMany()
                        .HasForeignKey("DocumentAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ingestion_jobs_document_assets_document_asset_id");

                    b.HasOne("PracticeX.Domain.Sources.SourceObject", null)
                        .WithMany()
                        .HasForeignKey("SourceObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ingestion_jobs_source_objects_source_object_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_jobs_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Evidence.EvidenceLink", b =>
                {
                    b.HasOne("PracticeX.Domain.Documents.DocumentAsset", null)
                        .WithMany()
                        .HasForeignKey("DocumentAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_links_document_assets_document_asset_id");

                    b.HasOne("PracticeX.Domain.Sources.SourceObject", null)
                        .WithMany()
                        .HasForeignKey("SourceObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_evidence_links_source_objects_source_object_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_links_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Organization.AppUser", b =>
                {
                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Organization.Facility", b =>
                {
                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_facilities_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Organization.Role", b =>
                {
                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roles_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Organization.RoleAssignment", b =>
                {
                    b.HasOne("PracticeX.Domain.Organization.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_role_assignments_facilities_facility_id");

                    b.HasOne("PracticeX.Domain.Organization.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignments_roles_role_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignments_tenants_tenant_id");

                    b.HasOne("PracticeX.Domain.Organization.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignments_users_user_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Sources.SourceConnection", b =>
                {
                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_connections_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Sources.SourceObject", b =>
                {
                    b.HasOne("PracticeX.Domain.Sources.SourceConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_objects_source_connections_connection_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_objects_tenants_tenant_id");
                });

            modelBuilder.Entity("PracticeX.Domain.Workflow.ReviewTask", b =>
                {
                    b.HasOne("PracticeX.Domain.Organization.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_review_tasks_users_assigned_to_user_id");

                    b.HasOne("PracticeX.Domain.Organization.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_tasks_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
